---
- name: Disk Management Playbook
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Check if running as root or with sudo
      fail:
        msg: "This playbook requires root privileges"
      when: ansible_effective_user_id != 0
  roles:
    - role: disk_management
      tags:
        - disk
        - storage